# Generated by Django 4.1 on 2023-06-04 10:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="TestUser",
            fields=[
                ("userNum", models.IntegerField(primary_key=True, serialize=False)),
                ("userId", models.CharField(max_length=10)),
                ("userPw", models.CharField(max_length=20)),
                ("userName", models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name="TestList",
            fields=[
                ("listNum", models.AutoField(primary_key=True, serialize=False)),
                ("listTitle", models.CharField(max_length=50)),
                ("listContent", models.TextField()),
                ("listCheck", models.IntegerField()),
                (
                    "userNum",
                    models.ForeignKey(
                        db_column="userNum",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="myapp.testuser",
                    ),
                ),
            ],
        ),
    ]
